#
# Copyright (C) 2008-2019 Dennis <op@TossP.com>
# Copyright (C) 2018 XiaoShan mivm.cn
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for k3screenctrl
LUCI_TYPE:=app
LUCI_DEPENDS:=@PACKAGE_phicommk3-screenctrl +phicommk3-screenctrl
PKG_VERSION:=2.0.0
PKG_RELEASE:=1

PKG_LICENSE:=GPLv3
PKG_LICENSE_FILES:=LICENSE
PKG_MAINTAINER:=Dennis <op@TossP.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
